# Auto-generated by git-issue-compile-statuses — do not edit
# Source: .git-issue/statuses
STATUSES=("open" "in_progress" "review" "blocked" "deferred" "closed" )
STATUS_MODE="permissive"

status_color() {
    case "$1" in
        open) echo "default" ;;
        in_progress) echo "yellow" ;;
        review) echo "blue" ;;
        blocked) echo "red" ;;
        deferred) echo "yellow" ;;
        closed) echo "gray" ;;
        *) echo "default" ;;
    esac
}

status_description() {
    case "$1" in
        open) echo "New issue, not yet started" ;;
        in_progress) echo "Actively being worked on" ;;
        review) echo "Awaiting feedback or review" ;;
        blocked) echo "Blocked by a dependency" ;;
        deferred) echo "On hold, will revisit later" ;;
        closed) echo "Completed or resolved" ;;
        *) echo "" ;;
    esac
}

validate_transition() {
    local from="$1" to="$2"
    case "${from}→${to}" in
        open→in_progress|open→blocked|open→deferred|open→closed|in_progress→review|in_progress→blocked|in_progress→deferred|in_progress→closed|review→in_progress|review→closed|blocked→open|blocked→in_progress|deferred→open|deferred→in_progress|closed→open) return 0 ;;
        *) return 1 ;;
    esac
}
